/**
 * src/lib/packages.ts
 *
 * Typed access to the parsed package catalog. The JSON is generated by
 * scripts/sync-packages.ts and committed to src/data/packages.json.
 *
 * Astro inlines this JSON at build time, so consumers pay no runtime cost
 * beyond shipping the data they actually use to the client.
 */

import rawData from "../data/packages.json";

export interface Package {
  name: string;
  version: string;
  architecture: string;
  repoId: string;
  repoLabel: string;
  filename: string;
  downloadUrl: string;
  size: number;
  md5sum?: string;
  sha1?: string;
  sha256?: string;
  maintainer?: string;
  description?: string;
  descriptionShort: string;
  section?: string;
  homepage?: string;
  depends?: string;
  recommends?: string;
  suggests?: string;
  conflicts?: string;
  provides?: string;
  icon?: string;
}

export interface Repo {
  id: string;
  label: string;
}

export const REPOS: Repo[] = [
  { id: "apt-repo", label: "Community repo" },
  { id: "n9mirror-001", label: "Nokia core" },
  { id: "n9mirror-apps", label: "Nokia apps" },
  { id: "n9mirror-tools", label: "Developer tools" },
  { id: "openrepos", label: "OpenRepos" },
];

const packages: Package[] = rawData as Package[];

/** Full flat catalog. */
export function getAllPackages(): Package[] {
  return packages;
}

/**
 * All entries for one package name, sorted by version descending so the first
 * one is the "primary" version. (Sort is best-effort string-based; Debian's
 * real version comparator is more elaborate but rarely matters here.)
 */
export function getPackageVersions(name: string): Package[] {
  return packages
    .filter((p) => p.name === name)
    .slice()
    .sort((a, b) => compareVersionsDesc(a.version, b.version));
}

/**
 * Deduplicate to one row per package name, keeping the highest version we
 * have. Used by the list view, which shows "also in N repos" as a hint when
 * duplicates exist.
 */
export function getDeduplicatedPackages(): Array<Package & { repoCount: number }> {
  const byName = new Map<string, Package[]>();
  for (const pkg of packages) {
    const arr = byName.get(pkg.name);
    if (arr) arr.push(pkg);
    else byName.set(pkg.name, [pkg]);
  }

  const out: Array<Package & { repoCount: number }> = [];
  for (const [, versions] of byName) {
    const sorted = versions
      .slice()
      .sort((a, b) => compareVersionsDesc(a.version, b.version));
    out.push({ ...sorted[0], repoCount: versions.length });
  }
  // Stable alpha sort by name
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

/** Unique package names (used by getStaticPaths for detail pages). */
export function getUniquePackageNames(): string[] {
  const set = new Set<string>();
  for (const p of packages) set.add(p.name);
  return [...set];
}

/**
 * Parse a Depends-style field into a list of names. Strips version constraints
 * like "(>= 1.0)" and trims alternatives joined with " | " down to the first.
 * Returns at most ~20 entries to keep detail pages from exploding on packages
 * with absurd dependency lists.
 */
export function parseDependencyNames(field: string | undefined): string[] {
  if (!field) return [];
  return field
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => entry.split("|")[0].trim())
    .map((entry) => entry.replace(/\s*\([^)]*\)\s*$/, "").trim())
    .filter(Boolean)
    .slice(0, 40);
}

/**
 * Naive descending version compare. Splits on dot/dash/tilde, compares
 * numeric chunks numerically and alphabetic chunks lexically. Good enough
 * for picking a "newest" within our catalog.
 */
function compareVersionsDesc(a: string, b: string): number {
  if (a === b) return 0;
  const aParts = a.split(/[.\-~]/);
  const bParts = b.split(/[.\-~]/);
  const len = Math.max(aParts.length, bParts.length);
  for (let i = 0; i < len; i++) {
    const ap = aParts[i] ?? "";
    const bp = bParts[i] ?? "";
    if (ap === bp) continue;
    const aNum = parseInt(ap, 10);
    const bNum = parseInt(bp, 10);
    if (!Number.isNaN(aNum) && !Number.isNaN(bNum)) {
      if (aNum !== bNum) return bNum - aNum; // descending
    }
    return bp.localeCompare(ap); // descending
  }
  return 0;
}

/** Pretty-format byte sizes for UI display. */
export function formatSize(bytes: number | undefined): string {
  if (!bytes) return "";
  const units = ["B", "KB", "MB", "GB"];
  let i = 0;
  let n = bytes;
  while (n >= 1024 && i < units.length - 1) {
    n /= 1024;
    i++;
  }
  return n.toFixed(n < 10 && i > 0 ? 1 : 0) + " " + units[i];
}

/** Truncate a string to maxLen with an ellipsis. */
export function truncate(s: string, maxLen: number): string {
  if (s.length <= maxLen) return s;
  return s.slice(0, maxLen - 1).trimEnd() + "…";
}
